steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - functions
      - deploy
      - adauga_document
      - --gen2
      - --runtime=python312
      - --region=europe-west1
      - --trigger-http
      - --entry-point=adauga_document
      - --allow-unauthenticated
      - --source=.

timeout: 300s


