options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - functions
      - deploy
      - exporta_persoane
      - --gen2
      - --runtime=python312
      - --region=europe-west1
      - --trigger-http
      - --entry-point=exporta_persoane
      - --allow-unauthenticated
      - --source=cloud-functions/export_persoane_bucket
