steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - obtine_documente
      - --gen2
      - --runtime=python312
      - --region=europe-west1
      - --trigger-http
      - --entry-point=obtine_documente
      - --source=cloud-functions/obtine_documente
      - --allow-unauthenticated

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - functions
      - add-iam-policy-binding
      - obtine_documente
      - --gen2
      - --region=europe-west1
      - --member=allUsers
      - --role=roles/cloudfunctions.invoker

options:
  logging: CLOUD_LOGGING_ONLY
